# Generated by Django 5.2.3 on 2025-06-23 21:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#808080', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tag', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('asset_type', models.CharField(max_length=100)),
                ('impact', models.CharField(default='Low', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('end_of_life', models.DateField(blank=True, null=True)),
                ('location', models.CharField(default='US', max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('managed_by_group', models.CharField(blank=True, max_length=100)),
                ('managed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(default='Medium', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('requester_name', models.CharField(blank=True, help_text='Name of the person requesting help', max_length=100)),
                ('requester_email', models.EmailField(blank=True, max_length=100)),
                ('source', models.CharField(default='phone', max_length=20)),
                ('urgency', models.CharField(default='low', max_length=10)),
                ('impact', models.CharField(default='low', max_length=10)),
                ('group', models.CharField(default='Level 1 Helpdesk', max_length=50)),
                ('department', models.CharField(default='IT', max_length=50)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('subcategory', models.CharField(blank=True, max_length=50)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('watching_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('agent', models.ForeignKey(blank=True, help_text='The IT support agent assigned to this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.statuslabel')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.incident')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50)),
                ('old_value', models.CharField(blank=True, max_length=100, null=True)),
                ('new_value', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='reports.incident')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
