# Generated by Django 5.2.3 on 2025-06-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_usernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
